version: '3.8'

services:
  submasterdc:
    image: ghcr.io/danielcurly/submasterdc:v1.0.2
    container_name: submasterdc
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/SubMasterDC/data:/app/data # Bases de datos y configuracion
      - /volume1/docker/SubMasterDC/logs:/app/logs # Registros de procesamiento
      - /volume3/Datos:/data1 # Mapeo idéntico a Radarr (Películas)
      - /volume4/Datos2:/data2 # Mapeo idéntico a Sonarr/Radarr (Series y Películas Asia)
    ports:
      - "8086:8000"
    restart: unless-stopped
