#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Subtitle Format Converter
Supports subtitle formats: SRT and ASS
"""

import re
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass
from datetime import timedelta, datetime
from core.models import SubtitleEntry, SubtitleStyleConfig
from core.logger import app_logger

# SubmasterDC Signature
SIGNATURE_BRAND = "Subtitles generated by SubmasterDC"
SIGNATURE_URL = "https://github.com/Danielcurly/submasterdc"
SIGNATURE_TAG = "SubmasterDC Signature v1"


def read_submasterdc_signature(file_path: str) -> Optional[Dict[str, str]]:
    """
    Read SubmasterDC signature from a subtitle file.
    Returns dict with keys: source, bilingual, primary, secondary, generated.
    Returns None if the file was not generated by SubmasterDC.
    """
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            head = f.read(2000)  # Only need to check the header
    except Exception:
        return None

    if SIGNATURE_TAG not in head and '[SubmasterDC ' not in head:
        return None

    meta = {}
    for line in head.splitlines():
        line = line.strip().lstrip('; ').strip()
        # ASS-style: "; Source: filename.mkv"
        # SRT-style: "[SubmasterDC v1|source:filename.mkv|bilingual:yes|...]"
        if line.startswith('[SubmasterDC '):
            # SRT hidden block format
            inner = line.strip('[]')
            for part in inner.split('|'):
                if ':' in part:
                    k, v = part.split(':', 1)
                    meta[k.strip().lower()] = v.strip()
            return meta if meta else None
        elif line.startswith('Source:'):
            meta['source'] = line.split(':', 1)[1].strip()
        elif line.startswith('Bilingual:'):
            parts = line.split('|')
            for p in parts:
                p = p.strip()
                if p.startswith('Bilingual:'):
                    meta['bilingual'] = p.split(':', 1)[1].strip()
                elif p.startswith('Primary:'):
                    meta['primary'] = p.split(':', 1)[1].strip()
                elif p.startswith('Secondary:'):
                    meta['secondary'] = p.split(':', 1)[1].strip()
        elif line.startswith('Generated:'):
            meta['generated'] = line.split(':', 1)[1].strip()

    return meta if meta else None


def _build_signature_meta(source_video: str = "",
                          bilingual: bool = False,
                          primary_lang: str = "",
                          secondary_lang: str = "") -> dict:
    """Build a signature metadata dict for injection into subtitle files."""
    return {
        'source': source_video,
        'bilingual': 'yes' if bilingual else 'no',
        'primary': primary_lang,
        'secondary': secondary_lang,
        'generated': datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
    }


class SubtitleConverter:
    """Subtitle format converter"""
    
    @staticmethod
    def parse_srt_time(time_str: str) -> int:
        """
        Parse SRT time format to milliseconds
        Format: HH:MM:SS,mmm
        """
        match = re.match(r'(\d{2}):(\d{2}):(\d{2}),(\d{3})', time_str)
        if not match:
            raise ValueError(f"Invalid SRT time format: {time_str}")
        
        hours, minutes, seconds, milliseconds = map(int, match.groups())
        return (hours * 3600 + minutes * 60 + seconds) * 1000 + milliseconds
    
    @staticmethod
    def format_srt_time(ms: int) -> str:
        """
        Format milliseconds to SRT time
        Format: HH:MM:SS,mmm
        """
        if ms < 0:
            ms = 0
        
        hours = ms // 3600000
        ms %= 3600000
        minutes = ms // 60000
        ms %= 60000
        seconds = ms // 1000
        milliseconds = ms % 1000
        
        return f"{hours:02d}:{minutes:02d}:{seconds:02d},{milliseconds:03d}"
    
    
    @staticmethod
    def format_ass_time(ms: int) -> str:
        """
        Format milliseconds to ASS/SSA time
        Format: H:MM:SS.cc (centiseconds)
        """
        if ms < 0:
            ms = 0
        
        hours = ms // 3600000
        ms %= 3600000
        minutes = ms // 60000
        ms %= 60000
        seconds = ms // 1000
        centiseconds = (ms % 1000) // 10
        
        return f"{hours}:{minutes:02d}:{seconds:02d}.{centiseconds:02d}"
    
    @staticmethod
    def parse_srt(content: str) -> List[SubtitleEntry]:
        """
        Parse SRT format using robust regex-based logic.
        Handles diverse line endings, spacing, and malformed blocks.
        """
        entries = []
        # Normalise line endings and split into potential blocks
        # We look for digits followed by a timecode line
        # Regex to match: Index \n Time --> Time \n Text
        pattern = re.compile(
            r'(\d+)\s*\n'                          # Index
            r'(\d{2}:\d{2}:\d{2}[,. ]\d{3})\s*-->\s*' # Start time
            r'(\d{2}:\d{2}:\d{2}[,. ]\d{3})\s*\n'     # End time
            r'(.*?(?=\n\s*\n\d+\s*\n\d{2}:\d{2}:|\Z))', # Text (non-greedy until next block or end)
            re.DOTALL
        )
        
        for match in pattern.finditer(content):
            try:
                index = int(match.group(1))
                start_str = match.group(2).replace('.', ',').replace(' ', ',')
                end_str = match.group(3).replace('.', ',').replace(' ', ',')
                text = match.group(4).strip()
                
                # Use a slightly more flexible time parser for the internal parts
                def flex_parse_time(ts):
                    h, m, s = ts.split(':')
                    s, ms = s.split(',')
                    return (int(h) * 3600 + int(m) * 60 + int(s)) * 1000 + int(ms)
                
                start_ms = flex_parse_time(start_str)
                end_ms = flex_parse_time(end_str)
                
                entries.append(SubtitleEntry(
                    index=index,
                    start_ms=start_ms,
                    end_ms=end_ms,
                    text=text
                ))
            except Exception as e:
                app_logger.warning(f"Error parsing subtitle block {index}: {e}")
                continue
        
        return entries

    @staticmethod
    def parse_ass(content: str) -> List[SubtitleEntry]:
        """
        Parse ASS format into SubtitleEntry list.
        Very basic implementation that extracts dialogue text and times.
        """
        entries = []
        # Find [Events] section
        events_idx = content.find("[Events]")
        if events_idx == -1:
            events_idx = 0
            
        # Dialogue lines: Dialogue: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        pattern = re.compile(r'Dialogue: \d+,(\d+:\d{2}:\d{2}\.\d{2}),(\d+:\d{2}:\d{2}\.\d{2}),[^,]+,[^,]*,\d+,\d+,\d+,[^,]*,(.*)')
        
        for idx, match in enumerate(pattern.finditer(content[events_idx:])):
            try:
                start_str, end_str, text = match.groups()
                
                # Convert ASS time (H:MM:SS.cc) to ms
                def ass_to_ms(t):
                    h, m, s = t.split(':')
                    s, cc = s.split('.')
                    return (int(h) * 3600 + int(m) * 60 + int(s)) * 1000 + int(cc) * 10
                
                start_ms = ass_to_ms(start_str)
                end_ms = ass_to_ms(end_str)
                
                # Clean up ASS tags (e.g. {\pos...}, {\rEng}, \N)
                text = re.sub(r'\{.*?\}', '', text)
                text = text.replace('\\N', '\n').strip()
                
                entries.append(SubtitleEntry(idx + 1, start_ms, end_ms, text))
            except Exception as e:
                app_logger.warning(f"Error parsing ASS block {idx}: {e}")
                continue
                
        return entries

    @staticmethod
    def to_srt(entries: List[SubtitleEntry],
               signature_meta: Optional[dict] = None) -> str:
        """
        Convert to SRT format
        
        Example:
        1
        00:00:01,000 --> 00:00:03,000
        Hello, world!
        """
        lines = []
        
        # Hidden metadata block (index 0, zero duration = invisible)
        if signature_meta:
            meta_parts = [f"SubmasterDC v1"]
            for k, v in signature_meta.items():
                if v:
                    meta_parts.append(f"{k}:{v}")
            meta_text = '[' + '|'.join(meta_parts) + ']'
            lines.append("0")
            lines.append("00:00:00,000 --> 00:00:00,000")
            lines.append(meta_text)
            lines.append("")
        
        for entry in entries:
            if not entry.text.strip():
                continue
            start = SubtitleConverter.format_srt_time(entry.start_ms)
            end = SubtitleConverter.format_srt_time(entry.end_ms)
            
            lines.append(f"{entry.index}")
            lines.append(f"{start} --> {end}")
            lines.append(entry.text.strip())
            lines.append("")  # Empty line separator
        
        # Visible branding as last subtitle
        if signature_meta and entries:
            last_end_ms = max(e.end_ms for e in entries)
            brand_start = last_end_ms + 5000  # 5s after last subtitle
            brand_end = brand_start + 3000     # 3s duration
            brand_idx = (entries[-1].index if entries else 0) + 1
            lines.append(f"{brand_idx}")
            lines.append(f"{SubtitleConverter.format_srt_time(brand_start)} --> {SubtitleConverter.format_srt_time(brand_end)}")
            lines.append(f"{SIGNATURE_BRAND}\n{SIGNATURE_URL}")
            lines.append("")
        
        return '\n'.join(lines)

    @staticmethod
    def save_srt(entries: List[SubtitleEntry], output_path: str,
                 signature_meta: Optional[dict] = None):
        """Save entries to an SRT file using shared logic"""
        content = SubtitleConverter.to_srt(entries, signature_meta=signature_meta)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
    

    
    @staticmethod
    def get_font_sizes(step: int) -> tuple:
        """Get primary and secondary font sizes for PlayRes 384x288"""
        scale = {
            1: 10, 2: 14, 3: 18, 4: 22, 
            5: 28, 6: 34, 7: 40
        }
        primary = scale.get(step, 22)
        secondary = primary // 2  # Maintain 50% proportion
        return primary, secondary

    @staticmethod
    def get_ass_header(style_config: SubtitleStyleConfig,
                       signature_meta: Optional[dict] = None,
                       is_bilingual: bool = False,
                       primary_lang: str = "",
                       secondary_lang: str = "") -> str:
        """Centralized ASS header generation with styles"""
        style = style_config or SubtitleStyleConfig()
        p_size, s_size = SubtitleConverter.get_font_sizes(style.font_size_step)
        
        # Build signature comments for ASS header
        sig_comments = "; Script generated by SubmasterDC"
        if signature_meta:
            sig_comments = f"; {SIGNATURE_TAG}"
            if signature_meta.get('source'):
                sig_comments += f"\n; Source: {signature_meta['source']}"
            bi = signature_meta.get('bilingual', 'no')
            pri = signature_meta.get('primary', primary_lang)
            sec = signature_meta.get('secondary', secondary_lang)
            sig_comments += f"\n; Bilingual: {bi} | Primary: {pri} | Secondary: {sec}"
            if signature_meta.get('generated'):
                sig_comments += f"\n; Generated: {signature_meta['generated']}"

        title = "Bilingual Subtitles" if is_bilingual else "Subtitles"
        
        # Primary style encodes 134 (GB2312) for Chinese support if needed, or 1 for others
        enc = "134" if is_bilingual else "1"

        header = f"""[Script Info]
{sig_comments}
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 384
PlayResY: 288

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft YaHei,{p_size},{style.primary_color},&H0000FFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,1,2,5,5,5,{enc}
Style: Eng,Microsoft YaHei,{s_size},{style.secondary_color},&H00000000,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,1,2,5,5,5,1
Style: Brand,Microsoft YaHei,8,&H44FFFFFF,&H00000000,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,5,5,5,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        return header

    @staticmethod
    def to_ass(entries: List[SubtitleEntry], 
               style_config: Optional[SubtitleStyleConfig] = None,
               style_name: str = "Default",
               signature_meta: Optional[dict] = None) -> str:
        """
        Convert to ASS (Advanced SubStation Alpha) format using style configuration
        """
        header = SubtitleConverter.get_ass_header(style_config, signature_meta)
        lines = [header]
        
        for entry in entries:
            start = SubtitleConverter.format_ass_time(entry.start_ms)
            end = SubtitleConverter.format_ass_time(entry.end_ms)
            
            # Handle newlines (ASS uses \N)
            text = entry.text.replace('\n', '\\N')
            
            lines.append(f"Dialogue: 0,{start},{end},{style_name},,0,0,0,,{text}")
        
        # Visible branding as last dialogue
        if signature_meta and entries:
            last_end_ms = max(e.end_ms for e in entries)
            brand_start = SubtitleConverter.format_ass_time(last_end_ms + 5000)
            brand_end = SubtitleConverter.format_ass_time(last_end_ms + 8000)
            lines.append(f"Dialogue: 0,{brand_start},{brand_end},Brand,,0,0,0,,{SIGNATURE_BRAND}\\N{SIGNATURE_URL}")
        
        return '\n'.join(lines)
    

    
    @staticmethod
    def convert_file(input_path: str, 
                    output_format: str,
                    output_path: Optional[str] = None,
                    style_config: Optional[SubtitleStyleConfig] = None,
                    signature_meta: Optional[dict] = None) -> str:
        """
        Convert subtitle file format (only SRT and ASS supported)
        """
        # Read input file
        with open(input_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        # Detect format and parse
        input_ext = Path(input_path).suffix.lower()
        if input_ext == '.ass':
            entries = SubtitleConverter.parse_ass(content)
        else:
            entries = SubtitleConverter.parse_srt(content)
        
        if not entries:
            raise ValueError("Failed to parse subtitle file or file is empty")
        
        # Convert to target format
        output_format = output_format.lower()
        if output_format == 'srt':
            output_content = SubtitleConverter.to_srt(entries, signature_meta=signature_meta)
        elif output_format == 'ass':
            output_content = SubtitleConverter.to_ass(entries, style_config=style_config, signature_meta=signature_meta)
        else:
            raise ValueError(f"Unsupported export format: {output_format}. Only 'srt' and 'ass' are supported.")
        
        # Generate output path
        if output_path is None:
            input_file = Path(input_path)
            output_path = str(input_file.parent / f"{input_file.stem}.{output_format}")
        
        # Write output file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(output_content)
        
        return output_path
    
    @staticmethod
    def convert_to_bilingual_ass(primary_srt_path: str, 
                                 secondary_srt_path: str, 
                                 output_path: str,
                                 style_config: Optional[SubtitleStyleConfig] = None,
                                 signature_meta: Optional[dict] = None) -> str:
        """Create a bilingual ASS file using style configurations"""
        style = style_config or SubtitleStyleConfig()
        
        with open(primary_srt_path, 'r', encoding='utf-8', errors='ignore') as f:
            p_content = f.read()
        with open(secondary_srt_path, 'r', encoding='utf-8', errors='ignore') as f:
            s_content = f.read()
            
        p_entries = SubtitleConverter.parse_srt(p_content)
        s_entries = SubtitleConverter.parse_srt(s_content)
        
        header = SubtitleConverter.get_ass_header(
            style, 
            signature_meta, 
            is_bilingual=True, 
            primary_lang=signature_meta.get('primary', '') if signature_meta else '',
            secondary_lang=signature_meta.get('secondary', '') if signature_meta else ''
        )

        lines = [header]
        
        # Time-based mapping for better alignment (handles missing/extra lines)
        s_idx = 0
        num_s = len(s_entries)
        
        for p in p_entries:
            start = SubtitleConverter.format_ass_time(p.start_ms)
            end = SubtitleConverter.format_ass_time(p.end_ms)
            p_text = p.text.replace('\n', '\\N')
            
            # Find best matching secondary entry by time
            s_text = ""
            # Since both are sorted, we can use a small window
            best_diff = 1000 # 1 second tolerance
            
            # Start from current index and look ahead/behind slightly
            st = max(0, s_idx - 5)
            en = min(num_s, s_idx + 10)
            
            for i in range(st, en):
                s = s_entries[i]
                diff = abs(s.start_ms - p.start_ms)
                if diff < best_diff:
                    best_diff = diff
                    s_text = s.text.replace('\\n', ' ').replace('\n', ' ')
                    s_idx = i # Update pointer for next iteration optimization
            
            if s_text:
                text = f"{p_text}\\N{{\\rEng}}{s_text}"
            else:
                text = p_text
            lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")
        
        # Visible branding as last dialogue
        if signature_meta and p_entries:
            last_end_ms = max(e.end_ms for e in p_entries)
            brand_start = SubtitleConverter.format_ass_time(last_end_ms + 5000)
            brand_end = SubtitleConverter.format_ass_time(last_end_ms + 8000)
            lines.append(f"Dialogue: 0,{brand_start},{brand_end},Brand,,0,0,0,,{SIGNATURE_BRAND}\\N{SIGNATURE_URL}")
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return output_path

    @staticmethod
    def convert_to_bilingual_srt(primary_srt_path: str, secondary_srt_path: str, output_path: str,
                                  signature_meta: Optional[dict] = None) -> str:
        """Create a bilingual SRT file using HTML font tags"""
        with open(primary_srt_path, 'r', encoding='utf-8', errors='ignore') as f:
            p_content = f.read()
        with open(secondary_srt_path, 'r', encoding='utf-8', errors='ignore') as f:
            s_content = f.read()
            
        p_entries = SubtitleConverter.parse_srt(p_content)
        s_entries = SubtitleConverter.parse_srt(s_content)
        lines = []
        
        # Hidden metadata block
        if signature_meta:
            meta_parts = [f"SubmasterDC v1"]
            for k, v in signature_meta.items():
                if v:
                    meta_parts.append(f"{k}:{v}")
            meta_text = '[' + '|'.join(meta_parts) + ']'
            lines.append("0")
            lines.append("00:00:00,000 --> 00:00:00,000")
            lines.append(meta_text)
            lines.append("")
        
        s_idx = 0
        num_s = len(s_entries)
        
        for p in p_entries:
            start = SubtitleConverter.format_srt_time(p.start_ms)
            end = SubtitleConverter.format_srt_time(p.end_ms)
            p_text = p.text
            
            # Time-based mapping
            s_text = ""
            best_diff = 1000
            st = max(0, s_idx - 5)
            en = min(num_s, s_idx + 10)
            
            for i in range(st, en):
                s = s_entries[i]
                diff = abs(s.start_ms - p.start_ms)
                if diff < best_diff:
                    best_diff = diff
                    s_text = s.text.replace('\\n', ' ').replace('\n', ' ')
                    s_idx = i
            
            lines.append(f"{p.index}")
            lines.append(f"{start} --> {end}")
            if s_text:
                lines.append(f"{p_text}\n<font size=\"12\">{s_text}</font>")
            else:
                lines.append(p_text)
            lines.append("")
        
        # Visible branding as last subtitle
        if signature_meta and p_entries:
            last_end_ms = max(e.end_ms for e in p_entries)
            brand_start = last_end_ms + 5000
            brand_end = brand_start + 3000
            brand_idx = (p_entries[-1].index if p_entries else 0) + 1
            lines.append(f"{brand_idx}")
            lines.append(f"{SubtitleConverter.format_srt_time(brand_start)} --> {SubtitleConverter.format_srt_time(brand_end)}")
            lines.append(f"{SIGNATURE_BRAND}\n{SIGNATURE_URL}")
            lines.append("")
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return output_path
    
    @staticmethod
    def convert_to_all_formats(input_path: str, 
                                style_config: Optional[SubtitleStyleConfig] = None) -> Dict[str, str]:
        """
        Convert subtitle to all supported export formats (SRT and ASS)
        """
        formats = ['srt', 'ass']
        results = {}
        
        for fmt in formats:
            try:
                output_path = SubtitleConverter.convert_file(input_path, fmt, style_config=style_config)
                results[fmt] = output_path
            except Exception as e:
                print(f"Failed to convert to {fmt} format: {e}")
        
        return results


# ============================================================================
# CLI Tool
# ============================================================================
def main():
    """Command line tool"""
    import sys
    
    if len(sys.argv) < 2:
        print("""
Subtitle Format Converter

Usage:
  python subtitle_converter.py convert <input.srt> <format>     # Convert to specified format (srt/ass)
  python subtitle_converter.py convert-all <input.srt>          # Convert to all formats (srt + ass)
  python subtitle_converter.py formats                          # Show supported formats

Supported export formats:
  - srt  : SubRip (Most universal)
  - ass  : Advanced SubStation Alpha (Rich Styles)

Example:
  python subtitle_converter.py convert movie.srt ass
  python subtitle_converter.py convert movie.zh.srt ass
  python subtitle_converter.py convert-all movie.srt
        """)
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == 'formats':
        print("\nSupported subtitle export formats:\n")
        print("1. SRT  - SubRip")
        print("   - Most universal format")
        print("   - Supported by almost all players")
        print("   - Recommended for most scenarios")
        print()
        print("2. ASS  - Advanced SubStation Alpha")
        print("   - Supports rich styles and effects")
        print("   - Common for Anime fansubs")
        print("   - Compatibility: VLC, MPC-HC, PotPlayer")
        print()
    
    elif command == 'convert':
        if len(sys.argv) < 4:
            print("Error: Missing parameters")
            print("Usage: python subtitle_converter.py convert <input.srt> <format>")
            sys.exit(1)
        
        input_path = sys.argv[2]
        output_format = sys.argv[3]
        
        try:
            output_path = SubtitleConverter.convert_file(input_path, output_format)
            print(f"✅ Conversion successful: {output_path}")
        except Exception as e:
            print(f"❌ Conversion failed: {e}")
            sys.exit(1)
    
    elif command == 'convert-all':
        if len(sys.argv) < 3:
            print("Error: Missing input file")
            print("Usage: python subtitle_converter.py convert-all <input.srt>")
            sys.exit(1)
        
        input_path = sys.argv[2]
        
        print(f"Converting {Path(input_path).name} to all formats...\n")
        
        results = SubtitleConverter.convert_to_all_formats(input_path)
        
        print("Conversion Results:")
        for fmt, path in results.items():
            print(f"  ✅ {fmt.upper()}: {Path(path).name}")
        
        print(f"\nGenerated {len(results)} files in total")
    
    else:
        print(f"Error: Unknown command '{command}'")
        sys.exit(1)


if __name__ == "__main__":
    main()